repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.4.1
    hooks:
      - id: baseline
        name: Ministry of Justice - Security scan

  - repo: local
    hooks:
      - id: lint
        name: Lint check
        entry: npm run validate:all
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: spellcheck
        name: Spell check
        entry: npm run spellcheck
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: pre-commit-hook
        name: Pre-commit hook validation
        entry: pre-commit validate-manifest
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: pre-commit-config
        name: Pre-commit configuration validation
        entry: pre-commit validate-config
        language: system
        pass_filenames: false
